# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 18:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.TextField()),
                ('title', models.CharField(max_length=50, unique=True)),
                ('transcription', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('created_time', models.TimeField()),
                ('created_date', models.DateField()),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
