# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 20:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='usernames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
