# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='title',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
