# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 18:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriber', '0002_auto_20170807_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='transcription',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
