# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriber', '0002_transcription_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
