# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriber', '0003_auto_20170808_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='created_date',
            field=models.DateField(default=datetime.date(2017, 8, 9)),
        ),
        migrations.AddField(
            model_name='transcription',
            name='created_time',
            field=models.TimeField(default=datetime.time(18, 31, 0, 652844)),
        ),
    ]
