# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriber', '0004_auto_20170809_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='created_time',
            field=models.TimeField(default=datetime.time(14, 27, 58, 465942)),
        ),
    ]
