# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriber', '0005_auto_20170809_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='created_time',
            field=models.TimeField(),
        ),
    ]
